site_name: PyScript

theme:
    name: material

    logo: assets/images/pyscript-black.svg

    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          primary: orange
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: orange
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: orange
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

    features:
        - content.code.copy
        - content.code.annotate

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
