name: "Update Docs"

on:
    push:
        branches:
            - main

jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  activate-environment: docs
                  environment-file: environment.yml

            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: '${{ secrets.DOCS_GITHUB_TOKEN }}'

            - name: Get Version
              id: version
              if: success()
              shell: bash
              run: echo "version=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

            - name: Update "gh-pages" branch
              shell: bash -l {0}
              run: |
                  git config user.name tedpatrick
                  git config user.email tpatrick@anaconda.com
                  git fetch origin gh-pages --depth=1
                  mike deploy --push --update-aliases ${{ steps.version.outputs.version }} latest
